### PR TITLE
Add httpRequestWithCredentials option

### PR DESCRIPTION
**Pull request by Sgajjar08**
… true for third-party cookies for issue 792

### CODE REVIEW

**Comment by tanem** [comment]
Thanks for the PR :+1:

I think this would be better as an option that defaults to `false`. Hopefully, you can follow your nose from [here](https://github.com/tanem/svg-injector/blob/master/src/svg-injector.ts#L23) to see how this new option might be implemented?

Let me know if you need a hand with any of the changes 🙏

**Comment by Sgajjar08** [comment]
Hello Tanem,
I made new changes and ran all the test cases everything works well but let me know if you want any changes in the code or format.
Thank you.

**Comment by Sgajjar08** [comment]
Hello Tanem,
Did you check the last commit? if not then please have a look and let me know if you want any changes to it.
Thank you.

**Comment by tanem** [comment]
@Sgajjar08 looking through the PR now. Will get back to you shortly.

**Comment by tanem** [comment]
Made a few tweaks. Just seeing if I can fix the build issue now.

**Comment by tanem** [comment]
@Sgajjar08 thanks for your patience! I've fixed the build issues, so will merge your PR now. Thanks for your contribution 🎉

**Pull request merged**
