### PR TITLE
Replace SVGElement type annotation with more specific SVGSVGElement 

### PR DESCRIPTION
**Pull request by steven-wolfman**
Replaced SVGElement with SVGSVGElement in all appearances, confirming that it is appropriate. This will give slightly better type information to users, should be backwards compatible with users using the (ancestor) SVGElement type, and allow future users to use the tighter SVGSVGElement type.

Here are the sets of replacements:

- types.ts: The key outward-facing change. I believe users of the library will receive a full SVG in either the `BeforeEach` callback (processing the SVG before it is injected) or the `Errback` callback (processing the SVG if there is an error). (What users do with the SVG is not relevant, as they cannot change its type for the module.)
- clone-svg.ts: I believe the source and resulting SVG are both full SVGs, not subtrees of an SVG. So, the appropriate type is SVGSVGElement
- load-svg-cached.ts, load-svg-uncached.ts, request-queue.ts, svg-cache.ts: The object returned by the AJAX request for an SVG should be a full SVG again, not a subtree. So, SVGSVGElement (and also when stored in the cache).

### CODE REVIEW

**Comment by steven-wolfman** [comment]
Huh.. CI failed because of lack of Browserstack credentials. This _is_ running locally with my browserstack credentials, but I'm not sure how to inform github of my credentials. Looking around.

**Comment by steven-wolfman** [comment]
OK. I added appropriate `secrets.BROWERSTACK_*` to my secret environment in github, but it still isn't running (after closing/reopening the pr). I assume that is because `.github/workflows/ci.yml` uses `pull_request` rather than [`pull_request_target`](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target), which seems pretty reasonable anyway. I'll leave rerunning CI to @tanem as owner.

**Comment by tanem** [comment]
Thanks @steven-wolfman, looking through this now 👍🏽

**Comment by tanem** [comment]
Yea, it was the `pull_request_target` thing and access to secrets. I enabled it temporarily for this PR, guess I might need to look at other alternatives in terms of how this repo is being built if I don't want to enable it permanently.

For now though all good - thanks again for the PR! I'll release it shortly.

**Pull request merged**
